/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsnirad.view;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import zavrsnirad.controller.ObradaOperater;
import zavrsnirad.model.Operater;
import zavrsnirad.util.AppException;

/**
 *
 * @author lovre
 */
public class ProzorRegistracija extends javax.swing.JFrame {

    private ObradaOperater obrada;

    /**
     * Creates new form ProzorRegistracija
     */
    public ProzorRegistracija() {
        initComponents();
        obrada = new ObradaOperater();
        setTitle("Registracija");
        getContentPane().setBackground(Color.white);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtOib = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistracija = new javax.swing.JButton();
        txtLozinka = new javax.swing.JPasswordField();
        txtPotvrda = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ime");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel2.setText("Prezime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 118, -1, -1));

        jLabel3.setText("Oib");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 169, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 226, -1, -1));

        jLabel5.setText("Lozinka");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 282, -1, -1));

        jLabel6.setText("Potvrdi lozinku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 338, -1, -1));
        getContentPane().add(txtIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 72, 191, -1));
        getContentPane().add(txtPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 135, 191, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 248, 191, -1));
        getContentPane().add(txtOib, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 186, 191, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Registracija");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 0, 100, 66));

        btnRegistracija.setText("Registriraj");
        btnRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistracijaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistracija, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 395, -1, -1));
        getContentPane().add(txtLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 304, 167, -1));

        txtPotvrda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPotvrdaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPotvrda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 366, 167, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 215));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistracijaActionPerformed
        obrada.setEntitet(new Operater());

        dodajOperatera();


    }//GEN-LAST:event_btnRegistracijaActionPerformed

    private void txtPotvrdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPotvrdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPotvrdaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistracija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JTextField txtOib;
    private javax.swing.JPasswordField txtPotvrda;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void dodajOperatera() {

        if (!Arrays.equals(txtLozinka.getPassword(), txtPotvrda.getPassword())) {

            JOptionPane.showMessageDialog(getRootPane(), "Lozinka nije potvrđena");

            return;
        }

        var o = obrada.getEntitet();

        o.setIme(txtIme.getText());

        o.setPrezime(txtPrezime.getText());
        o.setOib(txtOib.getText());
        o.setEmail(txtEmail.getText());
        System.out.println(txtLozinka.getPassword().length);

        if (lozinkaValjana(txtLozinka.getPassword())) {

            try {

                o.setLozinka(BCrypt.hashpw(new String(txtLozinka.getPassword()), BCrypt.gensalt()).toCharArray());
                obrada.create();

                JOptionPane.showMessageDialog(getRootPane(), "Uspješno ste se registrirali!!!");
                new ProzorLogin().setVisible(true);
                dispose();

            } catch (AppException ex) {

                JOptionPane.showMessageDialog(getRootPane(), ex.getPoruka());
                return;
            }
        } else {

            JOptionPane.showMessageDialog(getRootPane(), "Lozinka mora biti veća od 10 i mora sadržavati barem jedno veliko i malo slovo");

        }
    }

    private boolean lozinkaValjana(char[] password) {

        if (password.length > 10 && sadrziVelikoIMaloSlovo(password)) {
            
            return true;

        }else{

        return false;
        }
    }

    private boolean sadrziVelikoIMaloSlovo(char[] password) {
        int brojacMalih = 0;
        int brojacVelikih = 0;

        for (char c : password) {

            if (c >= 'a' && c <= 'z') {

                brojacMalih++;

            }
            if (c >= 'A' && c <= 'Z') {

                brojacVelikih++;
            }

        }

        if (brojacVelikih >= 1 && brojacMalih >= 1) {

            return true;
        } else {

            return false;
        }
    }
}
