/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsnirad.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.plaf.ProgressBarUI;
import org.hibernate.Session;
import zavrsnirad.util.HibernateUtil;

/**
 *
 * @author lovre
 */
public class SplashScreen extends javax.swing.JFrame {

    private JProgressBar p;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        p = new JProgressBar();
        setTitle("Učitavanje aplikacije...✈️");
        
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pbar.setBackground(new java.awt.Color(255, 255, 255));
        pbar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pbar.setForeground(new java.awt.Color(0, 255, 51));
        pbar.setRequestFocusEnabled(false);
        pbar.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Loading...");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avion3.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ucitaj() {
        new Ucitanje().start();

    }

    private class Ucitanje extends Thread {

        public void run() {

            Session s = HibernateUtil.getSession();
            p.setVisible(true);
            if (!s.getMetamodel().getEntities().isEmpty()) {
                
                for (int i = 0; i < 100; i++) {

                    pbar.setValue(i);
                    try {
                        Thread.sleep(30);
                    } catch (InterruptedException ex) {
                                
                    }

                }

                new ProzorLogin().setVisible(true);
                dispose();

            }

        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables
}
