/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsnirad.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.plaf.ProgressBarUI;
import org.hibernate.Session;
import zavrsnirad.util.HibernateUtil;

/**
 *
 * @author lovre
 */
public class SplashScreen extends javax.swing.JFrame {

    private JProgressBar p;

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        p = new JProgressBar();
        setTitle("Učitavanje aplikacije...✈️");
        getContentPane().setBackground(Color.white);
        
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pbar.setBackground(new java.awt.Color(255, 255, 255));
        pbar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pbar.setForeground(new java.awt.Color(102, 255, 102));
        pbar.setRequestFocusEnabled(false);
        pbar.setStringPainted(true);
        getContentPane().add(pbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 259, 22));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Loading...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 202, 40));

        jLabel3.setForeground(new java.awt.Color(254, 250, 250));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avion3.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 778, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ucitaj() {
        new Ucitanje().start();

    }

    private class Ucitanje extends Thread {

        public void run() {

            Session s = HibernateUtil.getSession();
            p.setVisible(true);
            if (!s.getMetamodel().getEntities().isEmpty()) {
                
                for (int i = 0; i < 100; i++) {

                    pbar.setValue(i);
                    try {
                        Thread.sleep(30);
                    } catch (InterruptedException ex) {
                                
                    }

                }

                new ProzorLogin().setVisible(true);
                dispose();

            }

        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables
}
